base_path: .

components:
  terraform:
    base_path: components/terraform
    apply_auto_approve: false
    deploy_run_init: true
    init_run_reconfigure: true

stacks:
  base_path: stacks
  included_paths:
    - "**/*.yaml"
  excluded_paths:
    - "**/_defaults.yaml"

logs:
  file: /dev/stderr
  level: Info
